version: '3'
services:
  
  my-service:
    build: .Dockerfile
    ports:
      - 8501:8501

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    depends_on:
      - my-service
    ports:
      - ${ACME_PORT:-80}:80  # for the certificate ACME challenge, overridable with env var to prevent possible port collisions on local development
      - "443:443"            # HTTPS
    volume:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      HOSTNAME: "${CADDY_HOSTNAME}"